"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TypeGenerationError = exports.MigrationError = exports.SchemaDiscoveryError = exports.QueryExecutionError = exports.RelationshipNotFoundError = exports.ValidationError = exports.DatabaseInitializationError = exports.ConnectionError = exports.ColumnNotFoundError = exports.TableNotFoundError = exports.NoormError = exports.NOORMME = exports.createQueryId = exports.logOnce = exports.expressionBuilder = void 0;
__exportStar(require("./kysely.js"), exports);
__exportStar(require("./query-creator.js"), exports);
__exportStar(require("./expression/expression.js"), exports);
var expression_builder_js_1 = require("./expression/expression-builder.js");
Object.defineProperty(exports, "expressionBuilder", { enumerable: true, get: function () { return expression_builder_js_1.expressionBuilder; } });
__exportStar(require("./expression/expression-wrapper.js"), exports);
__exportStar(require("./query-builder/where-interface.js"), exports);
__exportStar(require("./query-builder/returning-interface.js"), exports);
__exportStar(require("./query-builder/output-interface.js"), exports);
__exportStar(require("./query-builder/having-interface.js"), exports);
__exportStar(require("./query-builder/order-by-interface.js"), exports);
__exportStar(require("./query-builder/select-query-builder.js"), exports);
__exportStar(require("./query-builder/insert-query-builder.js"), exports);
__exportStar(require("./query-builder/update-query-builder.js"), exports);
__exportStar(require("./query-builder/delete-query-builder.js"), exports);
__exportStar(require("./query-builder/no-result-error.js"), exports);
__exportStar(require("./query-builder/join-builder.js"), exports);
__exportStar(require("./query-builder/function-module.js"), exports);
__exportStar(require("./query-builder/insert-result.js"), exports);
__exportStar(require("./query-builder/delete-result.js"), exports);
__exportStar(require("./query-builder/update-result.js"), exports);
__exportStar(require("./query-builder/on-conflict-builder.js"), exports);
__exportStar(require("./query-builder/aggregate-function-builder.js"), exports);
__exportStar(require("./query-builder/case-builder.js"), exports);
__exportStar(require("./query-builder/json-path-builder.js"), exports);
__exportStar(require("./query-builder/merge-query-builder.js"), exports);
__exportStar(require("./query-builder/merge-result.js"), exports);
__exportStar(require("./query-builder/order-by-item-builder.js"), exports);
__exportStar(require("./raw-builder/raw-builder.js"), exports);
__exportStar(require("./raw-builder/sql.js"), exports);
__exportStar(require("./query-executor/query-executor.js"), exports);
__exportStar(require("./query-executor/default-query-executor.js"), exports);
__exportStar(require("./query-executor/noop-query-executor.js"), exports);
__exportStar(require("./query-executor/query-executor-provider.js"), exports);
__exportStar(require("./query-compiler/default-query-compiler.js"), exports);
__exportStar(require("./query-compiler/compiled-query.js"), exports);
__exportStar(require("./schema/schema.js"), exports);
__exportStar(require("./schema/builders/create-table-builder.js"), exports);
__exportStar(require("./schema/builders/create-type-builder.js"), exports);
__exportStar(require("./schema/builders/drop-table-builder.js"), exports);
__exportStar(require("./schema/builders/drop-type-builder.js"), exports);
__exportStar(require("./schema/builders/create-index-builder.js"), exports);
__exportStar(require("./schema/builders/drop-index-builder.js"), exports);
__exportStar(require("./schema/builders/create-schema-builder.js"), exports);
__exportStar(require("./schema/builders/drop-schema-builder.js"), exports);
__exportStar(require("./schema/builders/column-definition-builder.js"), exports);
__exportStar(require("./schema/builders/foreign-key-constraint-builder.js"), exports);
__exportStar(require("./schema/builders/alter-table-builder.js"), exports);
__exportStar(require("./schema/builders/create-view-builder.js"), exports);
__exportStar(require("./schema/builders/refresh-materialized-view-builder.js"), exports);
__exportStar(require("./schema/builders/drop-view-builder.js"), exports);
__exportStar(require("./schema/builders/alter-column-builder.js"), exports);
__exportStar(require("./dynamic/dynamic.js"), exports);
__exportStar(require("./dynamic/dynamic-reference-builder.js"), exports);
__exportStar(require("./dynamic/dynamic-table-builder.js"), exports);
__exportStar(require("./driver/driver.js"), exports);
__exportStar(require("./driver/database-connection.js"), exports);
__exportStar(require("./driver/connection-provider.js"), exports);
__exportStar(require("./driver/default-connection-provider.js"), exports);
__exportStar(require("./driver/single-connection-provider.js"), exports);
__exportStar(require("./driver/dummy-driver.js"), exports);
__exportStar(require("./dialect/dialect.js"), exports);
__exportStar(require("./dialect/dialect-adapter.js"), exports);
__exportStar(require("./dialect/dialect-adapter-base.js"), exports);
__exportStar(require("./dialect/database-introspector.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-dialect.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-dialect-config.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-driver.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-query-compiler.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-introspector.js"), exports);
__exportStar(require("./dialect/sqlite/sqlite-adapter.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-dialect.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-dialect-config.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-driver.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-query-compiler.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-introspector.js"), exports);
__exportStar(require("./dialect/postgresql/postgresql-adapter.js"), exports);
__exportStar(require("./query-compiler/default-query-compiler.js"), exports);
__exportStar(require("./query-compiler/query-compiler.js"), exports);
// SQLite Migration System - Focused on SQLite automation and optimization
__exportStar(require("./sqlite-migration/index.js"), exports);
// Database Migration Tools - For SQLite <-> PostgreSQL migrations
__exportStar(require("./migration/index.js"), exports);
__exportStar(require("./plugin/kysely-plugin.js"), exports);
__exportStar(require("./plugin/camel-case/camel-case-plugin.js"), exports);
__exportStar(require("./plugin/deduplicate-joins/deduplicate-joins-plugin.js"), exports);
__exportStar(require("./plugin/with-schema/with-schema-plugin.js"), exports);
__exportStar(require("./plugin/parse-json-results/parse-json-results-plugin.js"), exports);
__exportStar(require("./plugin/handle-empty-in-lists/handle-empty-in-lists-plugin.js"), exports);
__exportStar(require("./plugin/handle-empty-in-lists/handle-empty-in-lists.js"), exports);
__exportStar(require("./operation-node/add-column-node.js"), exports);
__exportStar(require("./operation-node/add-constraint-node.js"), exports);
__exportStar(require("./operation-node/add-index-node.js"), exports);
__exportStar(require("./operation-node/aggregate-function-node.js"), exports);
__exportStar(require("./operation-node/alias-node.js"), exports);
__exportStar(require("./operation-node/alter-column-node.js"), exports);
__exportStar(require("./operation-node/alter-table-node.js"), exports);
__exportStar(require("./operation-node/and-node.js"), exports);
__exportStar(require("./operation-node/binary-operation-node.js"), exports);
__exportStar(require("./operation-node/case-node.js"), exports);
__exportStar(require("./operation-node/cast-node.js"), exports);
__exportStar(require("./operation-node/check-constraint-node.js"), exports);
__exportStar(require("./operation-node/collate-node.js"), exports);
__exportStar(require("./operation-node/column-definition-node.js"), exports);
__exportStar(require("./operation-node/column-node.js"), exports);
__exportStar(require("./operation-node/column-update-node.js"), exports);
__exportStar(require("./operation-node/common-table-expression-name-node.js"), exports);
__exportStar(require("./operation-node/common-table-expression-node.js"), exports);
__exportStar(require("./operation-node/constraint-node.js"), exports);
__exportStar(require("./operation-node/create-index-node.js"), exports);
__exportStar(require("./operation-node/create-schema-node.js"), exports);
__exportStar(require("./operation-node/create-table-node.js"), exports);
__exportStar(require("./operation-node/create-type-node.js"), exports);
__exportStar(require("./operation-node/create-view-node.js"), exports);
__exportStar(require("./operation-node/refresh-materialized-view-node.js"), exports);
__exportStar(require("./operation-node/data-type-node.js"), exports);
__exportStar(require("./operation-node/default-insert-value-node.js"), exports);
__exportStar(require("./operation-node/default-value-node.js"), exports);
__exportStar(require("./operation-node/delete-query-node.js"), exports);
__exportStar(require("./operation-node/drop-column-node.js"), exports);
__exportStar(require("./operation-node/drop-constraint-node.js"), exports);
__exportStar(require("./operation-node/drop-index-node.js"), exports);
__exportStar(require("./operation-node/drop-schema-node.js"), exports);
__exportStar(require("./operation-node/drop-table-node.js"), exports);
__exportStar(require("./operation-node/drop-type-node.js"), exports);
__exportStar(require("./operation-node/drop-view-node.js"), exports);
__exportStar(require("./operation-node/explain-node.js"), exports);
__exportStar(require("./operation-node/fetch-node.js"), exports);
__exportStar(require("./operation-node/foreign-key-constraint-node.js"), exports);
__exportStar(require("./operation-node/from-node.js"), exports);
__exportStar(require("./operation-node/function-node.js"), exports);
__exportStar(require("./operation-node/generated-node.js"), exports);
__exportStar(require("./operation-node/group-by-item-node.js"), exports);
__exportStar(require("./operation-node/group-by-node.js"), exports);
__exportStar(require("./operation-node/having-node.js"), exports);
__exportStar(require("./operation-node/identifier-node.js"), exports);
__exportStar(require("./operation-node/insert-query-node.js"), exports);
__exportStar(require("./operation-node/join-node.js"), exports);
__exportStar(require("./operation-node/json-operator-chain-node.js"), exports);
__exportStar(require("./operation-node/json-path-leg-node.js"), exports);
__exportStar(require("./operation-node/json-path-node.js"), exports);
__exportStar(require("./operation-node/json-reference-node.js"), exports);
__exportStar(require("./operation-node/limit-node.js"), exports);
__exportStar(require("./operation-node/list-node.js"), exports);
__exportStar(require("./operation-node/matched-node.js"), exports);
__exportStar(require("./operation-node/merge-query-node.js"), exports);
__exportStar(require("./operation-node/modify-column-node.js"), exports);
__exportStar(require("./operation-node/offset-node.js"), exports);
__exportStar(require("./operation-node/on-conflict-node.js"), exports);
__exportStar(require("./operation-node/on-duplicate-key-node.js"), exports);
__exportStar(require("./operation-node/on-node.js"), exports);
__exportStar(require("./operation-node/operation-node-source.js"), exports);
__exportStar(require("./operation-node/operation-node-transformer.js"), exports);
__exportStar(require("./operation-node/operation-node-visitor.js"), exports);
__exportStar(require("./operation-node/operation-node.js"), exports);
__exportStar(require("./operation-node/operator-node.js"), exports);
__exportStar(require("./operation-node/or-action-node.js"), exports);
__exportStar(require("./operation-node/or-node.js"), exports);
__exportStar(require("./operation-node/order-by-item-node.js"), exports);
__exportStar(require("./operation-node/order-by-node.js"), exports);
__exportStar(require("./operation-node/output-node.js"), exports);
__exportStar(require("./operation-node/over-node.js"), exports);
__exportStar(require("./operation-node/parens-node.js"), exports);
__exportStar(require("./operation-node/partition-by-item-node.js"), exports);
__exportStar(require("./operation-node/partition-by-node.js"), exports);
__exportStar(require("./operation-node/primary-key-constraint-node.js"), exports);
__exportStar(require("./operation-node/primitive-value-list-node.js"), exports);
__exportStar(require("./operation-node/query-node.js"), exports);
__exportStar(require("./operation-node/raw-node.js"), exports);
__exportStar(require("./operation-node/reference-node.js"), exports);
__exportStar(require("./operation-node/references-node.js"), exports);
__exportStar(require("./operation-node/rename-column-node.js"), exports);
__exportStar(require("./operation-node/rename-constraint-node.js"), exports);
__exportStar(require("./operation-node/returning-node.js"), exports);
__exportStar(require("./operation-node/schemable-identifier-node.js"), exports);
__exportStar(require("./operation-node/select-all-node.js"), exports);
__exportStar(require("./operation-node/select-modifier-node.js"), exports);
__exportStar(require("./operation-node/select-query-node.js"), exports);
__exportStar(require("./operation-node/selection-node.js"), exports);
__exportStar(require("./operation-node/set-operation-node.js"), exports);
__exportStar(require("./operation-node/simple-reference-expression-node.js"), exports);
__exportStar(require("./operation-node/table-node.js"), exports);
__exportStar(require("./operation-node/top-node.js"), exports);
__exportStar(require("./operation-node/tuple-node.js"), exports);
__exportStar(require("./operation-node/unary-operation-node.js"), exports);
__exportStar(require("./operation-node/unique-constraint-node.js"), exports);
__exportStar(require("./operation-node/update-query-node.js"), exports);
__exportStar(require("./operation-node/using-node.js"), exports);
__exportStar(require("./operation-node/value-list-node.js"), exports);
__exportStar(require("./operation-node/value-node.js"), exports);
__exportStar(require("./operation-node/values-node.js"), exports);
__exportStar(require("./operation-node/when-node.js"), exports);
__exportStar(require("./operation-node/where-node.js"), exports);
__exportStar(require("./operation-node/with-node.js"), exports);
__exportStar(require("./util/column-type.js"), exports);
__exportStar(require("./util/compilable.js"), exports);
__exportStar(require("./util/explainable.js"), exports);
__exportStar(require("./util/streamable.js"), exports);
__exportStar(require("./util/log.js"), exports);
__exportStar(require("./util/infer-result.js"), exports);
var log_once_js_1 = require("./util/log-once.js");
Object.defineProperty(exports, "logOnce", { enumerable: true, get: function () { return log_once_js_1.logOnce; } });
var query_id_js_1 = require("./util/query-id.js");
Object.defineProperty(exports, "createQueryId", { enumerable: true, get: function () { return query_id_js_1.createQueryId; } });
// NOORMME - No ORM, just magic!
var noormme_js_1 = require("./noormme.js");
Object.defineProperty(exports, "NOORMME", { enumerable: true, get: function () { return noormme_js_1.NOORMME; } });
__exportStar(require("./types/index.js"), exports);
// Agentic components
__exportStar(require("./agentic/SessionManager.js"), exports);
__exportStar(require("./agentic/ContextBuffer.js"), exports);
__exportStar(require("./agentic/VectorIndexer.js"), exports);
__exportStar(require("./agentic/Cortex.js"), exports);
__exportStar(require("./agentic/ActionJournal.js"), exports);
__exportStar(require("./agentic/ResourceMonitor.js"), exports);
__exportStar(require("./agentic/EpisodicMemory.js"), exports);
__exportStar(require("./agentic/CapabilityManager.js"), exports);
__exportStar(require("./agentic/PolicyEnforcer.js"), exports);
__exportStar(require("./agentic/SessionCompressor.js"), exports);
__exportStar(require("./agentic/PersonaManager.js"), exports);
__exportStar(require("./agentic/improvement/ReflectionEngine.js"), exports);
__exportStar(require("./agentic/improvement/KnowledgeDistiller.js"), exports);
__exportStar(require("./agentic/improvement/SovereignMetrics.js"), exports);
__exportStar(require("./agentic/improvement/SelfEvolution.js"), exports);
__exportStar(require("./agentic/improvement/EvolutionaryPilot.js"), exports);
__exportStar(require("./agentic/improvement/CortexJanitor.js"), exports);
__exportStar(require("./agentic/improvement/RecursiveReasoner.js"), exports);
__exportStar(require("./agentic/improvement/RuleEngine.js"), exports);
__exportStar(require("./agentic/improvement/ConflictResolver.js"), exports);
__exportStar(require("./agentic/improvement/CuriosityEngine.js"), exports);
__exportStar(require("./agentic/improvement/RitualOrchestrator.js"), exports);
__exportStar(require("./agentic/improvement/ActionRefiner.js"), exports);
__exportStar(require("./agentic/improvement/HiveLink.js"), exports);
__exportStar(require("./agentic/improvement/StrategicPlanner.js"), exports);
__exportStar(require("./agentic/improvement/AblationEngine.js"), exports);
__exportStar(require("./agentic/improvement/SelfTestRegistry.js"), exports);
__exportStar(require("./agentic/improvement/GovernanceManager.js"), exports);
__exportStar(require("./agentic/CognitiveRepository.js"), exports);
__exportStar(require("./helpers/agent-schema.js"), exports);
__exportStar(require("./helpers/schema-evolution.js"), exports);
// Error classes
var NoormError_js_1 = require("./errors/NoormError.js");
Object.defineProperty(exports, "NoormError", { enumerable: true, get: function () { return NoormError_js_1.NoormError; } });
Object.defineProperty(exports, "TableNotFoundError", { enumerable: true, get: function () { return NoormError_js_1.TableNotFoundError; } });
Object.defineProperty(exports, "ColumnNotFoundError", { enumerable: true, get: function () { return NoormError_js_1.ColumnNotFoundError; } });
Object.defineProperty(exports, "ConnectionError", { enumerable: true, get: function () { return NoormError_js_1.ConnectionError; } });
Object.defineProperty(exports, "DatabaseInitializationError", { enumerable: true, get: function () { return NoormError_js_1.DatabaseInitializationError; } });
Object.defineProperty(exports, "ValidationError", { enumerable: true, get: function () { return NoormError_js_1.ValidationError; } });
Object.defineProperty(exports, "RelationshipNotFoundError", { enumerable: true, get: function () { return NoormError_js_1.RelationshipNotFoundError; } });
Object.defineProperty(exports, "QueryExecutionError", { enumerable: true, get: function () { return NoormError_js_1.QueryExecutionError; } });
Object.defineProperty(exports, "SchemaDiscoveryError", { enumerable: true, get: function () { return NoormError_js_1.SchemaDiscoveryError; } });
Object.defineProperty(exports, "MigrationError", { enumerable: true, get: function () { return NoormError_js_1.MigrationError; } });
Object.defineProperty(exports, "TypeGenerationError", { enumerable: true, get: function () { return NoormError_js_1.TypeGenerationError; } });
// CLI commands (for programmatic usage)
__exportStar(require("./cli/commands/init.js"), exports);
__exportStar(require("./cli/commands/inspect.js"), exports);
__exportStar(require("./cli/commands/generate.js"), exports);
